"""Google Photos Takeout support.

Google's Takeout export pairs every photo/video with a JSON sidecar, but the
naming is famously inconsistent across export vintages:

  IMG_1234.JPG.json                          (classic)
  IMG_1234.JPG.supplemental-metadata.json     (2023+)
  IMG_1234.JPG.supplemental-met.json          (truncated)
  IMG_1234.JPG(1).json                        (de-duplicated counter)
  IMG_1234-edited.JPG  -> uses the original IMG_1234.JPG sidecar

This module finds the right sidecar with a layered matcher and parses the
fields PhotoPi cares about (capture time, GPS, description, album title).
"""
from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path

# Folders auto-generated by Google for date buckets - NOT real albums.
_DATE_FOLDER = re.compile(
    r"^(photos from \d{4}|fotos? (von|de|aus) \d{4}|\d{4})$", re.IGNORECASE
)
_EDITED = re.compile(r"^(.*)-(edited|bearbeitet|modifi\u00e9|ha editado)(\.[^.]+)$", re.I)
_COUNTER = re.compile(r"^(.*)\((\d+)\)(\.[^.]+)$")
_JSON_SUFFIX = re.compile(r"\.supplemental-met[a-z-]*\.json$|\.json$", re.IGNORECASE)


@dataclass
class TakeoutMeta:
    json_path: str | None = None
    title: str | None = None
    description: str | None = None
    taken_at: datetime | None = None
    lat: float | None = None
    lon: float | None = None
    altitude: float | None = None
    people: list[str] = field(default_factory=list)
    favorite: bool = False


def is_album_folder(folder: Path) -> bool:
    """True if *folder* looks like a user album (not a date bucket)."""
    name = folder.name.strip()
    if _DATE_FOLDER.match(name):
        return False
    # Only treat as an album if it sits inside a "Google Photos" tree.
    return any("google photos" in p.lower() for p in folder.parts)


def album_name_for(folder: Path) -> str | None:
    """Resolve the album name for a folder, preferring its metadata.json."""
    if not is_album_folder(folder):
        return None
    meta = folder / "metadata.json"
    if meta.is_file():
        try:
            data = json.loads(meta.read_text(encoding="utf-8"))
            title = data.get("title")
            if title:
                return str(title).strip()
        except (OSError, json.JSONDecodeError):
            pass
    return folder.name.strip()


def find_sidecar(media_name: str, json_names: set[str]) -> str | None:
    """Return the JSON sidecar filename for *media_name*, or None.

    *json_names* is the set of '.json' filenames in the same directory.
    """
    if not json_names:
        return None

    candidates: list[str] = [
        f"{media_name}.json",
        f"{media_name}.supplemental-metadata.json",
    ]

    # De-duplication counter:  name(1).jpg  ->  name.jpg(1).json
    counter = _COUNTER.match(media_name)
    if counter:
        base, num, ext = counter.groups()
        candidates += [
            f"{base}{ext}({num}).json",
            f"{base}{ext}({num}).supplemental-metadata.json",
        ]

    # Edited derivative -> reuse the original's sidecar.
    edited = _EDITED.match(media_name)
    if edited:
        original = f"{edited.group(1)}{edited.group(3)}"
        candidates += [
            f"{original}.json",
            f"{original}.supplemental-metadata.json",
        ]

    for cand in candidates:
        if cand in json_names:
            return cand

    # Fuzzy pass: Google truncates long sidecar names. Strip the json suffix
    # from each candidate file and keep the one sharing the longest prefix.
    best: tuple[int, str] | None = None
    for jn in json_names:
        core = _JSON_SUFFIX.sub("", jn)
        if not core:
            continue
        common = _common_prefix_len(core, media_name)
        # Require a substantial shared prefix to avoid false positives.
        if common >= 8 and common >= min(len(core), len(media_name)) - 4:
            if best is None or common > best[0]:
                best = (common, jn)
    return best[1] if best else None


def parse_sidecar(json_path: str | Path) -> TakeoutMeta:
    """Parse a Takeout JSON sidecar into a TakeoutMeta."""
    meta = TakeoutMeta(json_path=str(json_path))
    try:
        data = json.loads(Path(json_path).read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return meta

    meta.title = data.get("title")
    desc = data.get("description")
    meta.description = desc.strip() if isinstance(desc, str) and desc.strip() else None

    taken = data.get("photoTakenTime") or data.get("creationTime") or {}
    ts = taken.get("timestamp")
    if ts:
        try:
            meta.taken_at = datetime.fromtimestamp(int(ts), tz=timezone.utc).replace(
                tzinfo=None
            )
        except (ValueError, OSError, OverflowError):
            pass

    geo = data.get("geoData") or data.get("geoDataExif") or {}
    lat, lon = geo.get("latitude"), geo.get("longitude")
    # Google writes 0.0/0.0 when GPS is absent - treat that as missing.
    if isinstance(lat, (int, float)) and isinstance(lon, (int, float)):
        if abs(lat) > 1e-7 or abs(lon) > 1e-7:
            meta.lat, meta.lon = round(lat, 7), round(lon, 7)
            alt = geo.get("altitude")
            if isinstance(alt, (int, float)) and alt != 0:
                meta.altitude = float(alt)

    people = data.get("people") or []
    meta.people = [p["name"] for p in people if isinstance(p, dict) and p.get("name")]

    fav = data.get("favorited")
    meta.favorite = bool(fav) if fav is not None else False
    return meta


def _common_prefix_len(a: str, b: str) -> int:
    n = 0
    for ca, cb in zip(a, b):
        if ca != cb:
            break
        n += 1
    return n
